### ISSUE TITLE
Under Tweetbot 2.5, replying to new tweets does not work.

### ISSUE THREAD

**Issue by MTWomg** [lucifr/Tweetbot-for-Mac-ColorScheme#10]
In Tweetbot 2.5, the reply system changed. This change appears to impact the modified color scheme - when you click the reply button, nothing happens. This doesn't matter much at the moment due to the whole DRM bug thing, but it would still be nice to get this fixed in case we get lucky and 2.5.1 fixes the 'crashing after 1 minute' DRM bug.

**Comment by MTWomg** [comment]
I fixed this. Here's the new Plist.


[Colors.plist.zip](https://github.com/lucifr/Tweetbot-for-Mac-ColorScheme/files/968998/Colors.plist.zip)

**Comment by mimed** [comment]
The app is crashing everytime, even using the fix MTWomg provided above. Any help?
