### ISSUE TITLE
Hearts are yellow on tweet detail view

### ISSUE THREAD

**Issue by joshvickerson** [lucifr/Tweetbot-for-Mac-ColorScheme#6]
Liked tweets have a red heart in the timeline, but on the tweet detail view they're still yellow.
![screen shot 2016-02-02 at 11 21 26 am](https://cloud.githubusercontent.com/assets/2325487/12755861/2a007b50-c99f-11e5-83ef-094c839fbf68.png)

**Comment by lucifr** [comment]
It should be fixed with https://github.com/lucifr/Tweetbot-for-Mac-ColorScheme/commit/bde6f26e8f2eaf8ae42f3ede8c388993c366dfb2

Thanks for the report!
