### ISSUE TITLE
Blank windows on v2.4

### ISSUE THREAD

**Issue by megagator** [lucifr/Tweetbot-for-Mac-ColorScheme#8]
![screen shot 2016-05-19 at 17 28 51](https://cloud.githubusercontent.com/assets/6308213/15410349/3939c5f8-1de7-11e6-9c63-63dbc70ea60b.png)

After updating Tweetbot to version 2.4, the default Colors works as expected, but swapping in these dark Colors breaks all window drawing

**Comment by lucifr** [comment]
Please try the latest commit and report back. Thank you. 

https://github.com/lucifr/Tweetbot-for-Mac-ColorScheme/commit/f344007e77b5f33ec31dd17f5e476920af8e41ff

**Comment by megagator** [comment]
Dark mode is back in business, fantastic!
